[package]
name = "terminal_chess_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20"
rand = "0.8.5"
shakmaty = { version = "0.24.0" }
